DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, `NAME` VARCHAR(50), `STATE` VARCHAR(50), `COUNTRY` VARCHAR(50));

INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('SAN FRANCISCO', 'CA', 'US');
/*
CREATE  TABLE SMS_T_SEND(
  SMSID
  BIZTYPE
  MSGID
  SEQUENCEID
  SENDID
  RECEIVER
  CONTENT
STATUS
SENDCOUNT
CREATETIME
UPDATETIME
)

CREATE  TABLE SMS_T_SEND_HIS(
  SMSID
  BIZTYPE
  MSGID
  SEQUENCEID
  SENDID
  RECEIVER
  CONTENT
STATUS
SENDCOUNT
CREATETIME
UPDATETIME
)
*/
